### ISSUE TITLE
How do I check/uncheck with idealRadioCheck function?

### ISSUE THREAD

**Issue by hardsubs** [elclanrs/jq-idealforms#66]
Is there any quick usage example? Using prop makes option unchecked, but keeps it visually checked. Thanks

**Comment by elclanrs** [comment]
Can you try to trigger a change event on the checkbox?

``` javascript
$('#checkbox').trigger('change');
```

Or you can try to trigger a click event.

**Comment by hardsubs** [comment]
great, it worked, thanks a lot!
